remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: 👨‍💻 <span style="font-size: 0.8em;">based in michigan</span>

